### ISSUE TITLE
Port theme to Hugo/Forestry

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-theme-novela#1]
This theme.
https://github.com/narative/gatsby-theme-novela

I think we should set up two repos. One with the content, which we can serve as the sample site, and this repo, with the theme files. 

demo repo for content, etc https://github.com/theNewDynamic/theme-demo

- [ ] Port content and basic Hugo site structure to `theme-demo` as though it's a user's site.
- [ ] Add this repo as a Git submodule to the `theme-demo` site.
- [ ] Create theme logic. Even though this doesn't need to be like one of our internal sites, use some of the best practices from our existing sites (baseof template, etc. we can chat about this)
- [ ] Set up a simple, Hugo-centric asset pipeline.
    - [ ] Use SCSS for CSS. 
    - [ ] Use (let's figure this out, but maybe Webpack) for JS

**Comment by budparr** [comment]
believe this is done; please let us know if otherwise.
